### ISSUE TITLE
Variables are not highlighted properly when used in place of a function name in a function call

### ISSUE THREAD

**Issue by Stratus3D** [vim-erlang/vim-erlang-runtime#33]
In this example:

    module:FunName(Params)

`FunName` is highlighted as an atom instead of a variable. It has to be a variable in all cases because it starts with a capital letter and is not wrapped in single quotes. `Params` is highlighted as a variable as expected. This is the only scenario I have come across where a variable name isn't highlight as such.

I am using Vim 7.3 on OSX with the solarized dark theme. 

Screenshot:
![screen shot 2016-03-22 at 4 19 45 pm](https://cloud.githubusercontent.com/assets/1520926/13966684/03a55846-f04a-11e5-958b-ec0e1d04b180.png)

In this case `FunName` should be blue as well.

**Comment by hcs42** [comment]
@Stratus3D I created a fix in my [mod_func branch][1]. Could you test it? Thank you.

[1]: https://github.com/hcs42/vim-erlang-runtime/commits/mod_func

**Comment by Stratus3D** [comment]
Looks good to me. Thanks!

![screen shot 2016-03-28 at 5 34 00 pm](https://cloud.githubusercontent.com/assets/1520926/14090970/5e2e7cd2-f50b-11e5-99f8-52eeabfdbce1.png)
