### ISSUE TITLE
vim-erlang-runtime not being invoked for indenting code for *.erl

### ISSUE THREAD

**Issue by asridharan** [vim-erlang/vim-erlang-runtime#38]
I followed the instructions for installing `vim-erlang-runtime`. I can see that the plugins have been installed using `scriptnames` command and `:set runtimepath?` . However, ther is no auto indentation that is taking place in my existing *.erl file? This is my existing ~/.vimrc

```
set ai
set textwidth=70
set number
set tabstop=2
set shiftwidth=2
set expandtab
set runtimepath^=~/.vim/bundle/vim-erlang-runtime/
setlocal spell spelllang=en_us
set spellfile=$HOME/.vim/spell/en.utf-8.add
set switchbuf+=newtab
let Gtags_No_Auto_Jump = 1
let Gtags_VerticalWindow = 1
execute pathogen#infect()
```

**Comment by hcs42** [comment]
To use automatic indentation in Vim, you need to add this to your vimrc:

    filetype plugin indent on

If you have a recent Vim, you don't actually need this GitHub repository, because `vim-erlang-runtime` is built into Vim.
